apiVersion: v1
kind: Pod
metadata:
  name: iopingpod
spec:
  restartPolicy: Never
  containers:
  - name: ioping
    image: hpestorage/ioping:latest
    command: ["sleep", "infinity"]
    securityContext:
      privileged: true
    volumeMounts:
    - name: devdir
      mountPath: /host-dev
      readOnly: true
  volumes:
  - name: devdir
    hostPath:
      path: /dev
      type: Directory
